SET ECHO ON
DROP TABLE uniform CASCADE CONSTRAINTS;
DROP TABLE marcher CASCADE CONSTRAINTS;
DROP TABLE drumMajor CASCADE CONSTRAINTS;
DROP TABLE season CASCADE CONSTRAINTS;
DROP TABLE show CASCADE CONSTRAINTS;
DROP TABLE song CASCADE CONSTRAINTS;
DROP TABLE composer CASCADE CONSTRAINTS;
DROP TABLE participation CASCADE CONSTRAINTS;
DROP TRIGGER participation_IC4_tr;
DROP TABLE leadConductor CASCADE CONSTRAINTS;
DROP TABLE showLineup CASCADE CONSTRAINTS;
SET ECHO OFF
SELECT table_name FROM user_tables;
SELECT trigger_name FROM user_triggers;